In [15]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 200)

In [16]:
DATA_DIR = Path("../data/raw")

csv_files = list(DATA_DIR.rglob("*.csv"))

print(f"Found {len(csv_files)} CSV files:\n")

for file in csv_files:
    print(file)

Found 17 CSV files:

../data/raw/understat/player_stats.csv
../data/raw/understat/game_stats.csv
../data/raw/global_results/Match_Results.csv
../data/raw/global_results/Penalty_Shootouts.csv
../data/raw/global_results/Goal_Scorers.csv
../data/raw/transfermarkt/game_lineups.csv
../data/raw/transfermarkt/competitions.csv
../data/raw/transfermarkt/appearances.csv
../data/raw/transfermarkt/countries.csv
../data/raw/transfermarkt/player_valuations.csv
../data/raw/transfermarkt/game_events.csv
../data/raw/transfermarkt/transfers.csv
../data/raw/transfermarkt/players.csv
../data/raw/transfermarkt/games.csv
../data/raw/transfermarkt/club_games.csv
../data/raw/transfermarkt/national_teams.csv
../data/raw/transfermarkt/clubs.csv

In [17]:
def audit_csv(file_path):
    
    print("\n" + "="*80)
    print(f"FILE: {file_path.name}")
    print("="*80)

    try:
        df = pd.read_csv(file_path)

        print(f"\nShape: {df.shape[0]:,} rows x {df.shape[1]} columns")

        print("\nColumns:")
        print(list(df.columns))

        print("\nData Types:")
        print(df.dtypes)

        print("\nMissing Values:")
        missing = df.isnull().sum()
        missing = missing[missing > 0]

        if len(missing) == 0:
            print("No missing values")
        else:
            print(missing.sort_values(ascending=False))

        print("\nSample Rows:")
        display(df.head())

    except Exception as e:
        print("ERROR:", e)

In [18]:
for file in csv_files:
    audit_csv(file)

================================================================================
FILE: player_stats.csv
================================================================================

Shape: 35,076 rows x 19 columns

Columns:
['player_id', 'name', 'season', 'position', 'games', 'goals', 'shots', 'time', 'xG', 'assists', 'xA', 'key_passes', 'team', 'yellow', 'red', 'npg', 'npxG', 'xGChain', 'xGBuildup']

Data Types:
player_id       int64
name              str
season          int64
position          str
games           int64
goals           int64
shots           int64
time            int64
xG            float64
assists         int64
xA            float64
key_passes      int64
team              str
yellow          int64
red             int64
npg             int64
npxG          float64
xGChain       float64
xGBuildup     float64
dtype: object

Missing Values:
No missing values

Sample Rows:

,player_id,name,season,position,games,goals,shots,time,xG,assists,xA,key_passes,team,yellow,red,npg,npxG,xGChain,xGBuildup
0,1,Christian Mathenia,2018,GK,22,0,0,1933,0.000000,0,0.102488,1,Nuernberg,2,0,0,0.000000,1.944929,1.842441
1,1,Christian Mathenia,2017,GK,24,0,0,2160,0.000000,0,0.027247,1,Hamburger SV,2,0,0,0.000000,0.840935,0.813688
2,1,Christian Mathenia,2016,GK,14,0,0,1260,0.000000,0,0.015250,1,Hamburger SV,1,0,0,0.000000,1.346833,1.331583
3,1,Christian Mathenia,2015,GK,33,0,0,2970,0.000000,0,0.357929,5,Darmstadt,3,0,0,0.000000,3.300252,2.942322
4,2,György Garics,2015,DR,21,0,3,1796,0.044533,0,0.292171,3,Darmstadt,8,0,0,0.044533,1.418429,1.249879

================================================================================
FILE: game_stats.csv
================================================================================

Shape: 41,722 rows x 23 columns

Columns:
['id', 'league', 'season', 'club_name', 'home_away', 'xG', 'xGA', 'npxG', 'npxGA', 'ppda', 'ppda_allowed', 'deep', 'deep_allowed', 'scored', 'missed', 'xpts', 'result', 'date', 'wins', 'draws', 'loses', 'pts', 'npxGD']

Data Types:
id                int64
league              str
season            int64
club_name           str
home_away           str
xG              float64
xGA             float64
npxG            float64
npxGA           float64
ppda            float64
ppda_allowed    float64
deep              int64
deep_allowed      int64
scored            int64
missed            int64
xpts            float64
result              str
date                str
wins              int64
draws             int64
loses             int64
pts               int64
npxGD           float64
dtype: object

Missing Values:
No missing values

Sample Rows:

,id,league,season,club_name,home_away,xG,xGA,npxG,npxGA,ppda,ppda_allowed,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD
0,71,EPL,2014,Aston Villa,a,0.909774,0.423368,0.909774,0.423368,14.043478,4.125000,4,3,1,0,1.8322,w,2014-08-16 15:00:00,1,0,0,3,0.486406
1,71,EPL,2014,Aston Villa,h,0.507525,0.699295,0.507525,0.699295,15.523810,8.571429,4,7,0,0,1.1057,d,2014-08-23 12:45:00,0,1,0,1,-0.191770
2,71,EPL,2014,Aston Villa,h,0.639316,0.288880,0.639316,0.288880,28.153846,11.583333,6,7,2,1,1.6075,w,2014-08-31 13:30:00,1,0,0,3,0.350436
3,71,EPL,2014,Aston Villa,a,0.701676,0.728097,0.701676,0.728097,54.000000,6.500000,1,5,1,0,1.3252,w,2014-09-13 17:30:00,1,0,0,3,-0.026421
4,71,EPL,2014,Aston Villa,h,0.649013,1.362240,0.649013,1.362240,44.250000,7.727273,0,7,0,3,0.6912,l,2014-09-20 15:00:00,0,0,1,0,-0.713227

================================================================================
FILE: Match_Results.csv
================================================================================

Shape: 47,399 rows x 9 columns

Columns:
['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral']

Data Types:
date            str
home_team       str
away_team       str
home_score    int64
away_score    int64
tournament      str
city            str
country         str
neutral        bool
dtype: object

Missing Values:
No missing values

Sample Rows:

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0,0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4,2,Friendly,London,England,False
2,1874-03-07,Scotland,England,2,1,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2,2,Friendly,London,England,False
4,1876-03-04,Scotland,England,3,0,Friendly,Glasgow,Scotland,False

================================================================================
FILE: Penalty_Shootouts.csv
================================================================================

Shape: 644 rows x 5 columns

Columns:
['date', 'home_team', 'away_team', 'winner', 'first_shooter']

Data Types:
date             str
home_team        str
away_team        str
winner           str
first_shooter    str
dtype: object

Missing Values:
first_shooter    414
dtype: int64

Sample Rows:

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

================================================================================
FILE: Goal_Scorers.csv
================================================================================

Shape: 44,362 rows x 8 columns

Columns:
['date', 'home_team', 'away_team', 'team', 'scorer', 'minute', 'own_goal', 'penalty']

Data Types:
date             str
home_team        str
away_team        str
team             str
scorer           str
minute       float64
own_goal        bool
penalty         bool
dtype: object

Missing Values:
minute    259
scorer     49
dtype: int64

Sample Rows:

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

================================================================================
FILE: game_lineups.csv
================================================================================

/var/folders/xv/z1b04xfs23944484l_sjy8pr0000gp/T/ipykernel_75637/2922757824.py:8: DtypeWarning: Columns (0: number) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Shape: 3,172,454 rows x 10 columns

Columns:
['game_lineups_id', 'date', 'game_id', 'player_id', 'club_id', 'player_name', 'type', 'position', 'number', 'team_captain']

Data Types:
game_lineups_id       str
date                  str
game_id             int64
player_id           int64
club_id             int64
player_name           str
type                  str
position              str
number             object
team_captain        int64
dtype: object

Missing Values:
position    3
dtype: int64

Sample Rows:

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,b2dbe01c3656b06c8e23e9de714e26bb,2013-07-27,2317258,1443,610,Christian Poulsen,substitutes,Defensive Midfield,5,0
1,b50a3ec6d52fd1490aab42042ac4f738,2013-07-27,2317258,5017,610,Niklas Moisander,starting_lineup,Centre-Back,4,0
2,7d890e6d0ff8af84b065839966a0ec81,2013-07-27,2317258,9602,1090,Maarten Martens,substitutes,Left Winger,11,0
3,8c355268678b9bbc7084221b1f0fde36,2013-07-27,2317258,12282,610,Daley Blind,starting_lineup,Left-Back,17,0
4,76193074d549e5fdce4cdcbba0d66247,2013-07-27,2317258,25427,1090,Roy Beerens,starting_lineup,Right Winger,23,0

================================================================================
FILE: competitions.csv
================================================================================

Shape: 67 rows x 11 columns

Columns:
['competition_id', 'competition_code', 'name', 'sub_type', 'type', 'country_id', 'country_name', 'domestic_league_code', 'confederation', 'total_clubs', 'url']

Data Types:
competition_id              str
competition_code            str
name                        str
sub_type                    str
type                        str
country_id                int64
country_name                str
domestic_league_code        str
confederation               str
total_clubs             float64
url                         str
dtype: object

Missing Values:
total_clubs             16
country_name            13
domestic_league_code    13
dtype: int64

Sample Rows:

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
0,A1,bundesliga,bundesliga,first_tier,domestic_league,127,Austria,A1,europa,12.0,https://www.transfermarkt.co.uk/bundesliga/sta...
1,AFAC,afc-asian-cup,afc-asian-cup,afc_asian_cup,national_team_competition,-1,NaN,NaN,asien,NaN,https://www.transfermarkt.co.uk/afc-asian-cup/...
2,AFCN,africa-cup-of-nations,africa-cup-of-nations,africa_cup_of_nations,national_team_competition,-1,NaN,NaN,afrika,NaN,https://www.transfermarkt.co.uk/africa-cup-of-...
3,ARG1,torneo-apertura,torneo-apertura,first_tier,domestic_league,9,Argentina,ARG1,amerika,30.0,https://www.transfermarkt.co.uk/torneo-apertur...
4,AUS1,a-league-men,a-league-men,first_tier,domestic_league,12,Australia,AUS1,asien,12.0,https://www.transfermarkt.co.uk/a-league-men/s...

================================================================================
FILE: appearances.csv
================================================================================

Shape: 1,885,688 rows x 13 columns

Columns:
['appearance_id', 'game_id', 'player_id', 'player_club_id', 'player_current_club_id', 'date', 'player_name', 'competition_id', 'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played']

Data Types:
appearance_id               str
game_id                   int64
player_id                 int64
player_club_id            int64
player_current_club_id    int64
date                        str
player_name                 str
competition_id              str
yellow_cards              int64
red_cards                 int64
goals                     int64
assists                   int64
minutes_played            int64
dtype: object

Missing Values:
player_name    2
dtype: int64

Sample Rows:

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,76,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

================================================================================
FILE: countries.csv
================================================================================

Shape: 118 rows x 8 columns

Columns:
['country_id', 'country_name', 'country_code', 'confederation', 'total_clubs', 'total_players', 'average_age', 'url']

Data Types:
country_id         int64
country_name         str
country_code         str
confederation        str
total_clubs        int64
total_players      int64
average_age      float64
url                  str
dtype: object

Missing Values:
No missing values

Sample Rows:

,country_id,country_name,country_code,confederation,total_clubs,total_players,average_age,url
0,10,Armenia,ARM1,europa,10,265,24.8,https://www.transfermarkt.co.uk/wettbewerbe/na...
1,100,North Macedonia,MAZ1,europa,12,283,25.4,https://www.transfermarkt.co.uk/wettbewerbe/na...
2,103,Malaysia,MYS1,asien,13,399,28.3,https://www.transfermarkt.co.uk/wettbewerbe/na...
3,106,Malta,MT1N,europa,12,299,26.9,https://www.transfermarkt.co.uk/wettbewerbe/na...
4,107,Morocco,MAR1,afrika,16,499,27.2,https://www.transfermarkt.co.uk/wettbewerbe/na...

================================================================================
FILE: player_valuations.csv
================================================================================

Shape: 507,815 rows x 6 columns

Columns:
['player_id', 'date', 'market_value_in_eur', 'current_club_name', 'current_club_id', 'player_club_domestic_competition_id']

Data Types:
player_id                              int64
date                                     str
market_value_in_eur                    int64
current_club_name                        str
current_club_id                        int64
player_club_domestic_competition_id      str
dtype: object

Missing Values:
player_club_domestic_competition_id    22599
dtype: int64

Sample Rows:

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057,BE1
1,342216,2001-07-20,100000,Unknown,1241,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126,TR1
3,6893,2003-12-15,900000,Galatasaray,984,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398,IT1

================================================================================
FILE: game_events.csv
================================================================================

Shape: 1,272,141 rows x 11 columns

Columns:
['game_event_id', 'date', 'game_id', 'minute', 'type', 'club_id', 'club_name', 'player_id', 'description', 'player_in_id', 'player_assist_id']

Data Types:
game_event_id           str
date                    str
game_id               int64
minute                int64
type                    str
club_id               int64
club_name               str
player_id             int64
description             str
player_in_id        float64
player_assist_id    float64
dtype: object

Missing Values:
player_assist_id    1084239
player_in_id         643006
description           93180
dtype: int64

Sample Rows:

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
0,60d28dc455d299f5abdb65d7204fef40,2010-06-26,1026846,69,Cards,3589,South Korea,1772,"1. Yellow card , Foul",NaN,NaN
1,71280d139049475e02eb7627897da117,2010-06-26,1026846,38,Cards,3589,South Korea,27402,"1. Yellow card , Foul",NaN,NaN
2,dbb0d095a58423d8377d6b5b6b9f258f,2010-06-26,1026846,8,Goals,3449,Uruguay,44352,", Right-footed shot, 2. Tournament Goal Assist...",NaN,3408.0
3,6948606e52c10f6a2032ebe64355fe14,2010-06-26,1026846,80,Goals,3449,Uruguay,44352,", Right-footed shot, 3. Tournament Goal Assist...",NaN,72653.0
4,eb2ca121e9069fac2789c9e0be7cdbd3,2010-06-26,1026846,84,Substitutions,3449,Uruguay,44352,", Tactical",76213.0,NaN

================================================================================
FILE: transfers.csv
================================================================================

Shape: 40,208 rows x 10 columns

Columns:
['player_id', 'transfer_date', 'transfer_season', 'from_club_id', 'to_club_id', 'from_club_name', 'to_club_name', 'transfer_fee', 'market_value_in_eur', 'player_name']

Data Types:
player_id                int64
transfer_date              str
transfer_season            str
from_club_id             int64
to_club_id               int64
from_club_name             str
to_club_name               str
transfer_fee           float64
market_value_in_eur    float64
player_name                str
dtype: object

Missing Values:
market_value_in_eur    15849
transfer_fee           14387
dtype: int64

Sample Rows:

,player_id,transfer_date,transfer_season,from_club_id,to_club_id,from_club_name,to_club_name,transfer_fee,market_value_in_eur,player_name
0,467994,2030-06-30,25/26,5621,749,Reggiana,FC Empoli,0.0,700000.0,Luca Belardinelli
1,739277,2027-05-30,26/27,42055,589,Genclik Gücü,Antalyaspor,0.0,NaN,Yannick Nkurunziza
2,401533,2026-12-31,26/27,2029,2423,Ceará SC,Santa Clara,0.0,1500000.0,Matheusinho
3,468256,2026-12-31,26/27,2035,16655,Avaí FC,Atlético-MG B,0.0,700000.0,Daniel Penha
4,541914,2026-12-31,26/27,713,1124,BATE Borisov,Fakel Voronezh,0.0,225000.0,Anton Kovalev

================================================================================
FILE: players.csv
================================================================================

Shape: 47,701 rows x 26 columns

Columns:
['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'international_caps', 'international_goals', 'current_national_team_id', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur']

Data Types:
player_id                                 int64
first_name                                  str
last_name                                   str
name                                        str
last_season                               int64
current_club_id                           int64
player_code                                 str
country_of_birth                            str
city_of_birth                               str
country_of_citizenship                      str
date_of_birth                               str
sub_position                                str
position                                    str
foot                                        str
height_in_cm                            float64
contract_expiration_date                    str
agent_name                                  str
image_url                                   str
international_caps                      float64
international_goals                     float64
current_national_team_id                float64
url                                         str
current_club_domestic_competition_id        str
current_club_name                           str
market_value_in_eur                     float64
highest_market_value_in_eur             float64
dtype: object

Missing Values:
current_national_team_id                45247
international_goals                     30107
international_caps                      30107
agent_name                              22045
contract_expiration_date                16373
market_value_in_eur                     16194
highest_market_value_in_eur             16194
country_of_birth                         5166
foot                                     5097
city_of_birth                            4890
height_in_cm                             3657
first_name                               3091
current_club_domestic_competition_id     2269
current_club_name                        2269
sub_position                              461
country_of_citizenship                    273
date_of_birth                              49
dtype: int64

Sample Rows:

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,1981-01-30 00:00:00,Centre-Forward,Attack,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,1978-05-08 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

================================================================================
FILE: games.csv
================================================================================

Shape: 88,807 rows x 23 columns

Columns:
['game_id', 'competition_id', 'season', 'round', 'date', 'home_club_id', 'away_club_id', 'home_club_goals', 'away_club_goals', 'home_club_position', 'away_club_position', 'home_club_manager_name', 'away_club_manager_name', 'stadium', 'attendance', 'referee', 'url', 'home_club_formation', 'away_club_formation', 'home_club_name', 'away_club_name', 'aggregate', 'competition_type']

Data Types:
game_id                     int64
competition_id                str
season                      int64
round                         str
date                          str
home_club_id                int64
away_club_id                int64
home_club_goals             int64
away_club_goals             int64
home_club_position        float64
away_club_position        float64
home_club_manager_name        str
away_club_manager_name        str
stadium                       str
attendance                float64
referee                       str
url                           str
home_club_formation           str
away_club_formation           str
home_club_name                str
away_club_name                str
aggregate                     str
competition_type              str
dtype: object

Missing Values:
home_club_position        25314
away_club_position        25314
attendance                10808
home_club_formation        8195
away_club_formation        8069
home_club_manager_name      844
away_club_manager_name      844
referee                     678
stadium                     242
home_club_name               86
away_club_name               36
dtype: int64

Sample Rows:

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,NaN,Óscar Tabárez,Jung-moo Huh,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,NaN,Diego Maradona,Javier Aguirre,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,NaN,Bob Bradley,Milovan Rajevac,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,NaN,Joachim Löw,Fabio Capello,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,NaN,Bert van Marwijk,Vladimír Weiss,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition

================================================================================
FILE: club_games.csv
================================================================================

Shape: 177,614 rows x 11 columns

Columns:
['game_id', 'club_id', 'own_goals', 'own_position', 'own_manager_name', 'opponent_id', 'opponent_goals', 'opponent_position', 'opponent_manager_name', 'hosting', 'is_win']

Data Types:
game_id                    int64
club_id                    int64
own_goals                  int64
own_position             float64
own_manager_name             str
opponent_id                int64
opponent_goals             int64
opponent_position        float64
opponent_manager_name        str
hosting                      str
is_win                     int64
dtype: object

Missing Values:
own_position             50628
opponent_position        50628
own_manager_name          1688
opponent_manager_name     1688
dtype: int64

Sample Rows:

,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
0,1026846,3449,2,NaN,Óscar Tabárez,3589,1,NaN,Jung-moo Huh,Home,1
1,1026846,3589,1,NaN,Jung-moo Huh,3449,2,NaN,Óscar Tabárez,Away,0
2,1026847,3437,3,NaN,Diego Maradona,6303,1,NaN,Javier Aguirre,Home,1
3,1026847,6303,1,NaN,Javier Aguirre,3437,3,NaN,Diego Maradona,Away,0
4,1027001,3441,2,NaN,Milovan Rajevac,3505,1,NaN,Bob Bradley,Away,1

================================================================================
FILE: national_teams.csv
================================================================================

Shape: 118 rows x 17 columns

Columns:
['national_team_id', 'name', 'team_code', 'country_id', 'country_name', 'country_code', 'confederation', 'team_image_url', 'squad_size', 'average_age', 'foreigners_number', 'foreigners_percentage', 'total_market_value', 'coach_name', 'fifa_ranking', 'last_season', 'url']

Data Types:
national_team_id           int64
name                         str
team_code                    str
country_id                 int64
country_name                 str
country_code                 str
confederation                str
team_image_url               str
squad_size                 int64
average_age              float64
foreigners_number          int64
foreigners_percentage    float64
total_market_value       float64
coach_name               float64
fifa_ranking               int64
last_season                int64
url                          str
dtype: object

Missing Values:
coach_name               118
foreigners_percentage      5
total_market_value         3
confederation              1
dtype: int64

Sample Rows:

,national_team_id,name,team_code,country_id,country_name,country_code,confederation,team_image_url,squad_size,average_age,foreigners_number,foreigners_percentage,total_market_value,coach_name,fifa_ranking,last_season,url
0,10521,San Marino,san-marino,144,San Marino,SMR1,UEFA,https://tmssl.akamaized.net//images/flagge/hea...,24,24.9,17,70.8,995000.0,NaN,211,2025,https://www.transfermarkt.co.uk/san-marino/sta...
1,10533,Andorra,andorra,5,Andorra,AND2,UEFA,https://tmssl.akamaized.net//images/flagge/hea...,26,29.2,11,42.3,3380000.0,NaN,173,2025,https://www.transfermarkt.co.uk/andorra/starts...
2,11953,Montenegro,montenegro,216,Montenegro,MNE1,UEFA,https://tmssl.akamaized.net//images/flagge/hea...,26,28.3,24,92.3,60130001.0,NaN,81,2025,https://www.transfermarkt.co.uk/montenegro/sta...
3,13342,Guatemala,guatemala,58,Guatemala,GU1A,CONCACAF,https://tmssl.akamaized.net//images/flagge/hea...,21,25.2,6,28.6,5330000.0,NaN,96,2025,https://www.transfermarkt.co.uk/guatemala/star...
4,13497,Uganda,uganda,176,Uganda,UGL1,CAF,https://tmssl.akamaized.net//images/flagge/hea...,28,28.0,23,82.1,8700000.0,NaN,88,2025,https://www.transfermarkt.co.uk/uganda/startse...

================================================================================
FILE: clubs.csv
================================================================================

Shape: 796 rows x 17 columns

Columns:
['club_id', 'club_code', 'name', 'domestic_competition_id', 'total_market_value', 'squad_size', 'average_age', 'foreigners_number', 'foreigners_percentage', 'national_team_players', 'stadium_name', 'stadium_seats', 'net_transfer_record', 'coach_name', 'last_season', 'filename', 'url']

Data Types:
club_id                      int64
club_code                      str
name                           str
domestic_competition_id        str
total_market_value         float64
squad_size                   int64
average_age                float64
foreigners_number            int64
foreigners_percentage      float64
national_team_players        int64
stadium_name                   str
stadium_seats                int64
net_transfer_record            str
coach_name                     str
last_season                  int64
filename                       str
url                            str
dtype: object

Missing Values:
total_market_value       796
coach_name               706
foreigners_percentage     58
average_age               38
dtype: int64

Sample Rows:

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
0,10,arminia-bielefeld,Arminia Bielefeld,L1,NaN,27,25.3,15,55.6,4,SchücoArena,26515,+€5.90m,NaN,2021,../data/raw/transfermarkt-scraper/2021/clubs.j...,https://www.transfermarkt.co.uk/arminia-bielef...
1,10004,paris-fc,Paris Football Club,FR1,NaN,31,28.7,17,54.8,9,Stade Jean Bouin,19904,€-72.30m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/paris-fc/start...
2,10010,esporte-clube-bahia,Esporte Clube Bahia,BRA1,NaN,32,26.7,6,18.8,3,Arena Fonte Nova,47364,+€8.14m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/esporte-clube-...
3,1003,leicester-city,Leicester City,GB1,NaN,29,25.9,17,58.6,9,King Power Stadium,32259,+€57.30m,Steve Cooper,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/leicester-city...
4,1005,us-lecce,Unione Sportiva Lecce,IT1,NaN,27,25.3,23,85.2,13,Ettore Giardiniero,31559,+€8.62m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...

In [19]:
summary = []

for file in csv_files:

    try:
        df = pd.read_csv(file)

        summary.append({
            "dataset": file.name,
            "rows": len(df),
            "columns": len(df.columns),
            "missing_cells": int(df.isnull().sum().sum()),
            "memory_mb": round(
                df.memory_usage(deep=True).sum() / 1024 / 1024,
                2
            )
        })

    except:
        pass

summary_df = pd.DataFrame(summary)

summary_df.sort_values(
    "rows",
    ascending=False
)

/var/folders/xv/z1b04xfs23944484l_sjy8pr0000gp/T/ipykernel_75637/2602649918.py:6: DtypeWarning: Columns (0: number) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

                  dataset     rows  columns  missing_cells  memory_mb
5        game_lineups.csv  3172454       10              3    1390.57
7         appearances.csv  1885688       13              2     620.26
10        game_events.csv  1272141       11        1820425     511.15
9   player_valuations.csv   507815        6          22599     108.12
14         club_games.csv   177614       11         104632      46.71
13              games.csv    88807       23          80430      96.77
12            players.csv    47701       26         203489      60.27
2       Match_Results.csv    47399        9              0      19.04
4        Goal_Scorers.csv    44362        8            308      14.82
1          game_stats.csv    41722       23              0      18.54
11          transfers.csv    40208       10          30236      14.72
0        player_stats.csv    35076       19              0      10.98
16              clubs.csv      796       17           1598       0.56
3   Penalty_Shootouts.csv      644        5            414       0.19
15     national_teams.csv      118       17            127       0.07
8           countries.csv      118        8              0       0.04
6        competitions.csv       67       11             42       0.04

In [22]:
# Using your exact working relative paths
important_files = {
    "Transfermarkt": [
        "../data/raw/transfermarkt/players.csv",
        "../data/raw/transfermarkt/appearances.csv",
        "../data/raw/transfermarkt/games.csv",
        "../data/raw/transfermarkt/game_events.csv",
        "../data/raw/transfermarkt/club_games.csv",
        "../data/raw/transfermarkt/national_teams.csv"
    ],
    "Understat": [
        "../data/raw/understat/player_stats.csv",
        "../data/raw/understat/game_stats.csv"
    ],
    "Global Results": [
        "../data/raw/global_results/Match_Results.csv"
    ]
}

print("=" * 60)
print("📋 EXTRACTING ACTUAL COLUMN NAMES")
print("=" * 60)

for source, paths in important_files.items():
    print(f"\nFor {source}:")
    for path_str in paths:
        path = Path(path_str)
        if path.exists():
            try:
                # nrows=1 loads instantly without reading millions of data rows
                df = pd.read_csv(path, nrows=1)
                print(f"\n{path.name} columns:")
                print(df.columns.tolist())
            except Exception as e:
                print(f"❌ Error reading {path.name}: {e}")
        else:
            print(f"\n⚠️ File not found: {path_str}")

============================================================
📋 EXTRACTING ACTUAL COLUMN NAMES
============================================================

For Transfermarkt:

players.csv columns:
['player_id', 'first_name', 'last_name', 'name', 'last_season', 'current_club_id', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'height_in_cm', 'contract_expiration_date', 'agent_name', 'image_url', 'international_caps', 'international_goals', 'current_national_team_id', 'url', 'current_club_domestic_competition_id', 'current_club_name', 'market_value_in_eur', 'highest_market_value_in_eur']

appearances.csv columns:
['appearance_id', 'game_id', 'player_id', 'player_club_id', 'player_current_club_id', 'date', 'player_name', 'competition_id', 'yellow_cards', 'red_cards', 'goals', 'assists', 'minutes_played']

games.csv columns:
['game_id', 'competition_id', 'season', 'round', 'date', 'home_club_id', 'away_club_id', 'home_club_goals', 'away_club_goals', 'home_club_position', 'away_club_position', 'home_club_manager_name', 'away_club_manager_name', 'stadium', 'attendance', 'referee', 'url', 'home_club_formation', 'away_club_formation', 'home_club_name', 'away_club_name', 'aggregate', 'competition_type']

game_events.csv columns:
['game_event_id', 'date', 'game_id', 'minute', 'type', 'club_id', 'club_name', 'player_id', 'description', 'player_in_id', 'player_assist_id']

club_games.csv columns:
['game_id', 'club_id', 'own_goals', 'own_position', 'own_manager_name', 'opponent_id', 'opponent_goals', 'opponent_position', 'opponent_manager_name', 'hosting', 'is_win']

national_teams.csv columns:
['national_team_id', 'name', 'team_code', 'country_id', 'country_name', 'country_code', 'confederation', 'team_image_url', 'squad_size', 'average_age', 'foreigners_number', 'foreigners_percentage', 'total_market_value', 'coach_name', 'fifa_ranking', 'last_season', 'url']

For Understat:

player_stats.csv columns:
['player_id', 'name', 'season', 'position', 'games', 'goals', 'shots', 'time', 'xG', 'assists', 'xA', 'key_passes', 'team', 'yellow', 'red', 'npg', 'npxG', 'xGChain', 'xGBuildup']

game_stats.csv columns:
['id', 'league', 'season', 'club_name', 'home_away', 'xG', 'xGA', 'npxG', 'npxGA', 'ppda', 'ppda_allowed', 'deep', 'deep_allowed', 'scored', 'missed', 'xpts', 'result', 'date', 'wins', 'draws', 'loses', 'pts', 'npxGD']

For Global Results:

Match_Results.csv columns:
['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral']

## Key Analysis of Core Tables

In [23]:
# Base directory for Transfermarkt files
base_path = Path("../data/raw/transfermarkt")

# 1. Load the 4 specific datasets
print("⏳ Loading datasets...")
appearances = pd.read_csv(base_path / "appearances.csv")
games = pd.read_csv(base_path / "games.csv")
players = pd.read_csv(base_path / "players.csv")
club_games = pd.read_csv(base_path / "club_games.csv")
print("✅ Datasets loaded successfully.\n")

# ==========================================
# STANDARD INSPECTION (.head() and .info())
# ==========================================
datasets = {
    "appearances": appearances,
    "games": games,
    "players": players,
    "club_games": club_games
}

for name, df in datasets.items():
    print("=" * 80)
    print(f"📋 INSPECTING DATASET: {name}")
    print("=" * 80)
    
    print(f"\n🔹 {name}.head():")
    display(df.head())
    
    print(f"\n🔹 {name}.info():")
    df.info()
    print("\n")

# ==========================================
# SPECIFIC KEY INSPECTION
# ==========================================
print("=" * 80)
print("🔑 SPECIFIC KEY HEAD INSPECTION")
print("=" * 80)

print("\n🔹 appearances[['player_id', 'game_id']].head():")
display(appearances[['player_id', 'game_id']].head())

print("\n🔹 games[['game_id']].head():")
display(games[['game_id']].head())

print("\n🔹 players[['player_id']].head():")
display(players[['player_id']].head())

print("\n🔹 club_games[['game_id', 'club_id']].head():")
display(club_games[['game_id', 'club_id']].head())


# ==========================================
# JOIN VERIFICATION AUDIT
# ==========================================
print("\n" + "=" * 80)
print("🧐 JOIN CLEANLINESS VERIFICATION RESULTS")
print("=" * 80)

# Check 1: appearances.player_id ↕ players.player_id
app_players = set(appearances['player_id'].unique())
tot_players = set(players['player_id'].unique())
matched_players = app_players.intersection(tot_players)

print("\n1. Key Match: appearances.player_id ↕ players.player_id")
print(f"   - Unique players in appearances: {len(app_players):,}")
print(f"   - Unique players in players master: {len(tot_players):,}")
print(f"   - Overlapping/Matching players: {len(matched_players):,}")

if len(app_players) == len(matched_players):
    print("   ✅ CLEAN JOIN: Every single player in appearances exists in the players master file.")
else:
    missing_pct = ((len(app_players) - len(matched_players)) / len(app_players)) * 100
    print(f"   ⚠️  MISMATCH: {len(app_players) - len(matched_players):,} players in appearances ({missing_pct:.2f}%) are MISSING from the players master file.")

# Check 2: appearances.game_id ↕ games.game_id
app_games = set(appearances['game_id'].unique())
tot_games = set(games['game_id'].unique())
matched_games = app_games.intersection(tot_games)

print("\n2. Key Match: appearances.game_id ↕ games.game_id")
print(f"   - Unique games in appearances: {len(app_games):,}")
print(f"   - Unique games in games master: {len(tot_games):,}")
print(f"   - Overlapping/Matching games: {len(matched_games):,}")

if len(app_games) == len(matched_games):
    print("   ✅ CLEAN JOIN: Every single game recorded in appearances exists in the games master file.")
else:
    missing_pct = ((len(app_games) - len(matched_games)) / len(app_games)) * 100
    print(f"   ⚠️  MISMATCH: {len(app_games) - len(matched_games):,} games in appearances ({missing_pct:.2f}%) are MISSING from the games master file.")

⏳ Loading datasets...
✅ Datasets loaded successfully.

================================================================================
📋 INSPECTING DATASET: appearances
================================================================================

🔹 appearances.head():

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90
1,2233748_79232,2233748,79232,8841,2698,2012-07-05,Ruslan Abyshov,ELQ,0,0,0,0,90
2,2234413_42792,2234413,42792,6251,465,2012-07-05,Sander Puri,ELQ,0,0,0,0,45
3,2234418_73333,2234418,73333,1274,76,2012-07-05,Vegar Hedenstad,ELQ,0,0,0,0,90
4,2234421_122011,2234421,122011,195,3008,2012-07-05,Markus Henriksen,ELQ,0,0,0,1,90

🔹 appearances.info():
<class 'pandas.DataFrame'>
RangeIndex: 1885688 entries, 0 to 1885687
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           str
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    str
 6   player_name             str
 7   competition_id          str
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), str(4)
memory usage: 187.0 MB


================================================================================
📋 INSPECTING DATASET: games
================================================================================

🔹 games.head():

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,NaN,NaN,Óscar Tabárez,Jung-moo Huh,Nelson Mandela Bay Stadium,30597.0,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,NaN,NaN,Diego Maradona,Javier Aguirre,FNB-Stadium,84377.0,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,NaN,NaN,Bob Bradley,Milovan Rajevac,Royal Bafokeng Stadium,34976.0,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,NaN,NaN,Joachim Löw,Fabio Capello,Free State Stadium,40510.0,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,NaN,NaN,Bert van Marwijk,Vladimír Weiss,Moses Mabhida Stadion,61962.0,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Netherlands,Slovakia,2:1,national_team_competition

🔹 games.info():
<class 'pandas.DataFrame'>
RangeIndex: 88807 entries, 0 to 88806
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   game_id                 88807 non-null  int64
 1   competition_id          88807 non-null  str
 2   season                  88807 non-null  int64
 3   round                   88807 non-null  str
 4   date                    88807 non-null  str
 5   home_club_id            88807 non-null  int64
 6   away_club_id            88807 non-null  int64
 7   home_club_goals         88807 non-null  int64
 8   away_club_goals         88807 non-null  int64
 9   home_club_position      63493 non-null  float64
 10  away_club_position      63493 non-null  float64
 11  home_club_manager_name  87963 non-null  str
 12  away_club_manager_name  87963 non-null  str
 13  stadium                 88565 non-null  str
 14  attendance              77999 non-null  float64
 15  referee                 88129 non-null  str
 16  url                     88807 non-null  str
 17  home_club_formation     80612 non-null  str
 18  away_club_formation     80738 non-null  str
 19  home_club_name          88721 non-null  str
 20  away_club_name          88771 non-null  str
 21  aggregate               88807 non-null  str
 22  competition_type        88807 non-null  str
dtypes: float64(3), int64(6), str(14)
memory usage: 15.6 MB


================================================================================
📋 INSPECTING DATASET: players
================================================================================

🔹 players.head():

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,date_of_birth,sub_position,position,foot,height_in_cm,contract_expiration_date,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,1978-06-09 00:00:00,Centre-Forward,Attack,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,1980-08-06 00:00:00,Goalkeeper,Goalkeeper,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,1981-01-30 00:00:00,Centre-Forward,Attack,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,1978-05-08 00:00:00,Centre-Back,Defender,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,1981-03-18 00:00:00,Goalkeeper,Goalkeeper,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

🔹 players.info():
<class 'pandas.DataFrame'>
RangeIndex: 47701 entries, 0 to 47700
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   player_id                             47701 non-null  int64
 1   first_name                            44610 non-null  str
 2   last_name                             47701 non-null  str
 3   name                                  47701 non-null  str
 4   last_season                           47701 non-null  int64
 5   current_club_id                       47701 non-null  int64
 6   player_code                           47701 non-null  str
 7   country_of_birth                      42535 non-null  str
 8   city_of_birth                         42811 non-null  str
 9   country_of_citizenship                47428 non-null  str
 10  date_of_birth                         47652 non-null  str
 11  sub_position                          47240 non-null  str
 12  position                              47701 non-null  str
 13  foot                                  42604 non-null  str
 14  height_in_cm                          44044 non-null  float64
 15  contract_expiration_date              31328 non-null  str
 16  agent_name                            25656 non-null  str
 17  image_url                             47701 non-null  str
 18  international_caps                    17594 non-null  float64
 19  international_goals                   17594 non-null  float64
 20  current_national_team_id              2454 non-null   float64
 21  url                                   47701 non-null  str
 22  current_club_domestic_competition_id  45432 non-null  str
 23  current_club_name                     45432 non-null  str
 24  market_value_in_eur                   31507 non-null  float64
 25  highest_market_value_in_eur           31507 non-null  float64
dtypes: float64(6), int64(3), str(17)
memory usage: 9.5 MB


================================================================================
📋 INSPECTING DATASET: club_games
================================================================================

🔹 club_games.head():

,game_id,club_id,own_goals,own_position,own_manager_name,opponent_id,opponent_goals,opponent_position,opponent_manager_name,hosting,is_win
0,1026846,3449,2,NaN,Óscar Tabárez,3589,1,NaN,Jung-moo Huh,Home,1
1,1026846,3589,1,NaN,Jung-moo Huh,3449,2,NaN,Óscar Tabárez,Away,0
2,1026847,3437,3,NaN,Diego Maradona,6303,1,NaN,Javier Aguirre,Home,1
3,1026847,6303,1,NaN,Javier Aguirre,3437,3,NaN,Diego Maradona,Away,0
4,1027001,3441,2,NaN,Milovan Rajevac,3505,1,NaN,Bob Bradley,Away,1

🔹 club_games.info():
<class 'pandas.DataFrame'>
RangeIndex: 177614 entries, 0 to 177613
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   game_id                177614 non-null  int64
 1   club_id                177614 non-null  int64
 2   own_goals              177614 non-null  int64
 3   own_position           126986 non-null  float64
 4   own_manager_name       175926 non-null  str
 5   opponent_id            177614 non-null  int64
 6   opponent_goals         177614 non-null  int64
 7   opponent_position      126986 non-null  float64
 8   opponent_manager_name  175926 non-null  str
 9   hosting                177614 non-null  str
 10  is_win                 177614 non-null  int64
dtypes: float64(2), int64(6), str(3)
memory usage: 14.9 MB


================================================================================
🔑 SPECIFIC KEY HEAD INSPECTION
================================================================================

🔹 appearances[['player_id', 'game_id']].head():

   player_id  game_id
0      38004  2231978
1      79232  2233748
2      42792  2234413
3      73333  2234418
4     122011  2234421

🔹 games[['game_id']].head():

   game_id
0  1026846
1  1026847
2  1027001
3  1027002
4  1027048

🔹 players[['player_id']].head():

   player_id
0         10
1         26
2         65
3         77
4         80

🔹 club_games[['game_id', 'club_id']].head():

   game_id  club_id
0  1026846     3449
1  1026846     3589
2  1026847     3437
3  1026847     6303
4  1027001     3441

================================================================================
🧐 JOIN CLEANLINESS VERIFICATION RESULTS
================================================================================

1. Key Match: appearances.player_id ↕ players.player_id
   - Unique players in appearances: 28,736
   - Unique players in players master: 47,701
   - Overlapping/Matching players: 28,735
   ⚠️  MISMATCH: 1 players in appearances (0.00%) are MISSING from the players master file.

2. Key Match: appearances.game_id ↕ games.game_id
   - Unique games in appearances: 73,253
   - Unique games in games master: 88,807
   - Overlapping/Matching games: 73,253
   ✅ CLEAN JOIN: Every single game recorded in appearances exists in the games master file.